### ISSUE TITLE
Possibility to tag used ingredients in step

### ISSUE THREAD

**Issue by brmdv** [techhat/openrecipeformat#15]
This would make it possible for parsers to automatically sort the ingredients list chronologically, or to export recipes with the ingredients listed at each step.

```yaml
- step:
  Add the sugar and half of the flower to the bowl.
  ingredients:
  - sugar
  - flower:
    amounts: 
    - amount: 250
      unit: g
```
