### ISSUE TITLE
Example of recipe using duration

### ISSUE THREAD

**Issue by MasterOdin** [techhat/openrecipeformat#28]
Looking at https://open-recipe-format.readthedocs.io/en/latest/topics/tutorials/using-alerts.html, I am confused on exactly where this duration field would be included on a step. Per the reference spec for the [step dict](topics/reference/orf.html#steps), there is not `duration` field or anything else that might indicate duration, except perhaps embedding the duration in the step itself or in the notes field.

For a hypothetical duck procuttio recipe, a step may look like:

```yaml
steps:
  - step: Hang for about 7 days in a cool (50 to 60 degrees is optimal), humid place, like a garage, a basement or in an unlit fireplace.
```

Now, is the intention that the `7 days in the step be replaced with `7D` (which I would argue against as potentially leading to parsing ambiguities for durations), or have something like:

```yaml
steps:
  - step: Hang for about 7 days in a cool (50 to 60 degrees is optimal), humid place, like a garage, a basement or in an unlit fireplace.
    duration: 7D
```

Happy to add this @techhat  to the reference and update the schema, just need a bit of intended direction on what this meant.
